serverpod/serverpod_docs

docs/index.md
add docker desktop website to the docs 
it was missing from my machine and took me time to know that docker is  required the docs font is small and i skipped this part 😁
=> Update Get started page

versioned_docs/version-0.9.21/04-concepts/02-serialization.md
Very neat framework! came across this when going though the docs and filed a quick fix.
Keep up the great work!
=> Updated serialisation rules count in doc

docs/01-get-started.md
=> fix some typo (double the)

docs/05-concepts/01-working-with-endpoints.md
Closes: [#979](https://github.com/serverpod/serverpod/issues/979)
=> docs: Improve ip configuration settings in the documentation.

docs/05-concepts/01-working-with-endpoints.md, docs/05-concepts/02-protocol.md
Describe that we support UuidValue and Duration.
=> docs: Add additional supported types for protocols and endpoints.

docs/05-concepts/02-model.md, docs/05-concepts/06-database/11-migrations.md
Documentation for feature in PR: https://github.com/serverpod/serverpod/pull/1688
=> docs: Add how to opt out of migrations per table.

docs/05-concepts/06-database/03-relations/06-modules.md
Documentation for relation to modules feature in this PR: https://github.com/serverpod/serverpod/pull/1680
=> docs: Add relation to modules.

docs/01-get-started.md
Updates to match how the create process works now.
=> fix: Update docs after windows 1.2.0-RC3 test

docs/05-concepts/06-database/08-sort.md, docs/05-concepts/06-database/11-migrations.md, docs/12-upgrading/01-upgrade-to-one-point-two.md
Couple of documentation fixes after the release.
Closes: https://github.com/serverpod/serverpod/issues/1772
Closes: https://github.com/serverpod/serverpod/issues/1762
Closes: https://github.com/serverpod/serverpod/issues/1773
=> Documentation fixes after 1.2 release

versioned_docs/version-1.2.0/03-tutorials/01-first-app.mdx, versioned_docs/version-1.2.0/05-concepts/06-database/07-relation-queries.md, versioned_docs/version-1.2.0/05-concepts/06-database/09-pagination.md
=> fix: apply changes.

.github/workflows/deploy.yml, .github/workflows/test-build.yml, README.md
Add automatic documentation deploys.
=> ci: add automatic documentation deploys.

versioned_docs/version-1.2.0/05-concepts/06-database/03-relations/01-one-to-one.md
Added some punctuation and corrected a spelling mistake.
=> Minor documentation improvements in 01-one-to-one.md

docs/05-concepts/07-caching.md
Add documentation for the CacheMissHandler.
PR for the feature here: https://github.com/serverpod/serverpod/pull/847
=> fix: Add document the cache miss handler.

docs/05-concepts/06-database/06-filter.md, versioned_docs/version-1.2.0/05-concepts/06-database/06-filter.md
Add documentation for new empty set behavior with inSet and notInSet.
=> fix: document empty set behavior.

docs/12-upgrading/01-upgrade-to-two.md, package-lock.json
Add migration guide for int to bigint.
Documentation connected to this PR: https://github.com/serverpod/serverpod/pull/1194
=> fix: Add migration guide for int -> bigint.

docs/05-concepts/06-database/05-crud.md, docs/12-upgrading/01-upgrade-to-two.md
Documents the change of return type for the delete operations.
Code change PR: https://github.com/serverpod/serverpod/pull/2121
=> fix: Update return type for delete operations.

docs/index.md, versioned_docs/version-1.2.0/index.md
Update keynote to latest keynote.
=> fix: Update keynote to 1.2.

docs/12-upgrading/01-upgrade-to-two.md
Documents the breaking changes introduced here: https://github.com/serverpod/serverpod/pull/2249
=> fix: Update docs around removed fields.

docs/05-concepts/10-authentication/01-setup.md, versioned_docs/version-1.2.0/05-concepts/10-authentication/01-setup.md
This PR tries to close serverpod/serverpod#2245 and also holds the documentation part of serverpod/serverpod#2250.
Please let me know where there is room for improvement :)
=> Document auth config

.github/workflows/deploy.yml, README.md, docusaurus.config.js, package-lock.json, package.json
Adds a client side redirect for moved documentation pages.
This plugin generates a static html for the pages that have been removed and redirects on the client side to the new url.
=> fix: Add redirect for moved documentation pages.

docs/01-get-started.md
Add a link to the medium article describing how to get started with Serverpod Mini.
=> fix: Add link to medium article for Serverpod Mini.

docs/05-concepts/06-database/10-raw-access.md
This document was quite outdated and included functions that are not even there any more. Pretty much a rewrite from scratch.
=> Rewrote outdated raw sql queries docs to match latest parameter binding update

docs/index.md, versioned_docs/version-2.0.0/index.md
Updates the keynote video in version 2 and next to version 2.0.0 of Serverpod.
=> fix: Update keynote video to 2.0.0.

versioned_docs/version-2.0.0/05-concepts/06-database/10-raw-access.md
Updates the published version of the raw access page.
=> fix: update raw access page for 2.0 version.

docs/06-concepts/01-working-with-endpoints.md, docs/06-concepts/12-file-uploads.md
Fixes:
https://github.com/serverpod/serverpod/issues/2273
https://github.com/serverpod/serverpod/issues/1994
=> fix: Adds missing docs for file uploads and large payloads.

docs/06-concepts/15-streams.md
Adds a simple documentation for the new streaming methods.
These can be expanded if edge cases need further documentation.
Documents: https://github.com/serverpod/serverpod/issues/2338
=> fix: Add documentation for the new streaming methods.

docs/06-concepts/11-authentication/05-custom-overrides.md
Added 'Advanced authentication schemes' documentation to Authentication / Custom overrides section.
=> feat: Added 'Advanced authentication schemes' documentation to Authentication / Custom overrides section

docs/06-concepts/11-authentication/03-working-with-users.md, versioned_docs/version-2.0.0/05-concepts/10-authentication/03-working-with-users.md
Found a variable we forgot to update in 2.0 from a breaking change we made.
=> fix: Align docs with userId change in 2.0.

docs/06-concepts/06-database/05-crud.md
see https://github.com/serverpod/serverpod/discussions/2815
=> 2815: typos on CRUD page

docs/06-concepts/02-models.md
=> add info on scope=none

docs/06-concepts/06-database/07-relation-queries.md
* fix typos in the like example
* make pagination clearer by making the page size correspond to the offset
=> cleanup/clarification of relation-queries

docs/06-concepts/06-database/07-relation-queries.md, versioned_docs/version-1.2.0/05-concepts/06-database/07-relation-queries.md, versioned_docs/version-2.0.0/05-concepts/06-database/07-relation-queries.md, versioned_docs/version-2.1.0/06-concepts/06-database/07-relation-queries.md, versioned_docs/version-2.1.0/06-concepts/07-configuration.md
- Applies some fixes to earlier docs versions
- fixes `like` that should be `iLike`
=> fix: Apply fixes in previous docs as well

docs/06-concepts/18-testing/01-get-started.md, docs/06-concepts/18-testing/02-the-basics.md, docs/06-concepts/18-testing/03-advanced-examples.md, docs/06-concepts/18-testing/04-best-practises.md
- Changes the default folder
- Adds docs about tags
=> fix: change the default folder, add tag docs

docs/06-concepts/11-authentication/03-working-with-users.md, versioned_docs/version-2.0.0/05-concepts/10-authentication/03-working-with-users.md, versioned_docs/version-2.1.0/06-concepts/11-authentication/03-working-with-users.md
One more instance of getting userId
=> fix: Add null check to authentication info access.

versioned_docs/version-2.1.0/06-concepts/15-streams.md
fix: Remove incorrect experimental notice.
=> fix: Remove incorrect experimental notice.

docs/06-concepts/18-testing/01-get-started.md, docs/06-concepts/19-experimental.md
- chore: Remove test tools experimental flag.
=> chore: Remove test tools experimental flag.

docs/06-concepts/11-authentication/03-working-with-users.md, versioned_docs/version-1.1.1/05-concepts/09-authentication/03-working-with-users.md, versioned_docs/version-1.2.0/05-concepts/10-authentication/03-working-with-users.md, versioned_docs/version-2.0.0/05-concepts/10-authentication/03-working-with-users.md, versioned_docs/version-2.1.0/06-concepts/11-authentication/03-working-with-users.md, versioned_docs/version-2.2.0/06-concepts/11-authentication/03-working-with-users.md, versioned_docs/version-2.3.0/06-concepts/11-authentication/03-working-with-users.md
Closes:  https://github.com/serverpod/serverpod_docs/issues/230
=> docs: Redirect to the real user info class

docs/10-contribute.md, versioned_docs/version-2.3.0/10-contribute.md
Slimmed down the contributions page and referred to the updated version in the repository.
-----
=> fix: Refer to contribution guidelines in repository.

docs/03-capabilities.md, docs/06-concepts/20-experimental.md
Documentation for the experimental exception monitoring feature introduced in PRs:
https://github.com/serverpod/serverpod/pull/3187
https://github.com/serverpod/serverpod/pull/3249
=> docs: Experimental exception monitoring feature

docs/07-deployments/06-community-supported-deployments.md, versioned_docs/version-2.3.0/07-deployments/06-community-supported-deployments.md
related to https://github.com/serverpod/serverpod/pull/2124
Closes: https://github.com/serverpod/serverpod/issues/347
=> docs: Add community-supported VPS deployment documentation

.prettierrc, docusaurus.config.js, package-lock.json, package.json
Adds the google analytics property for better insights into which docs pages are most frequently used
=> feat: Add tracking

docs/06-concepts/02-models.md
Adds documentation for enum default values.
=> feat: Add documentation for enum defaults.

docs/06-concepts/06-database/01-connection.md, docs/06-concepts/07-configuration.md
The documentation for https://github.com/serverpod/serverpod/pull/3407
=> feat: Add documentation for database search paths configurable option.

docs/06-concepts/07-configuration.md, docs/06-concepts/12-file-uploads.md
=> docs: Adds docs for S3 and GCP access keys and ids

docusaurus.config.js
@vlidholt we need to add the link to the form (and double check that the wording is matching)
=> feat: Adds global banner for the course waitlist

docs/06-concepts/07-configuration.md, docusaurus.config.js, package-lock.json, package.json
=> feat: Adds config hierarchy chart

docusaurus.config.js
Change the urls to that the sitemap is correctly built.
=> fix: Update url so that sitemap is correctly generated.

.markdownlint.yaml, docs/06-concepts/06-database/01-connection.md, docs/06-concepts/06-database/03-relations/05-referential-actions.md, docs/06-concepts/06-database/08-transactions.md, docs/06-concepts/06-database/10-raw-access.md, docs/06-concepts/11-authentication/01-setup.md, docs/06-concepts/11-authentication/02-basics.md, docs/06-concepts/11-authentication/04-providers/06-custom-providers.md, docs/06-concepts/11-authentication/05-custom-overrides.md, docs/06-concepts/19-testing/01-get-started.md, docs/06-concepts/19-testing/02-the-basics.md, docs/index.md
For some reason another PR triggered a couple of linter issues.
This PR fixes these.
PR here: https://github.com/serverpod/serverpod_docs/pull/282
=> chore: Fix markdown lint issues

docs/06-concepts/05-sessions.md
Closes https://github.com/serverpod/serverpod/issues/3161 , https://github.com/serverpod/serverpod/issues/3419
=> docs: Document the Session API
