- versioned_docs/version-1.0.0/04-concepts/07-authentication.md
Hi, thanks for creating Serverpod! I was looking through the documentation, and this seems like a typo.
> fix: concepts->authentication typo

- docs/05-concepts/11-streams.md
As from v0.9.15 the `connectWebSocket` method has been deprecated in favour of `openStreamingConnection` but the docs still show the old method.
> fix: Update deprecated connectWebSocket to openStreamingConnection

- docs/05-concepts/01-working-with-endpoints.md
- docs/05-concepts/02-protocol.md
- docs/05-concepts/03-serialization.md
- Remove duplicated content.
- Add detailed info on how custom serializable objects work.
Resolves documentation comment on: https://github.com/serverpod/serverpod/issues/858
I have opted to not write about the fact that you are able to write `project:src/path/to/file.dart` in the generator.yaml file. While this is possible should we encourage people to copy-paste code between two projects manually?
> docs: Expand custom serialization section with examples.

- docs/01-get-started.md
- docs/02-capabilities.md
- docs/03-tutorials/01-first-app.mdx
- docs/05-concepts/02-model.md
- docs/05-concepts/04-exceptions.md
- docs/05-concepts/06-database/02-models.md
- docs/05-concepts/06-database/03-relations/01-one-to-one.md
- docs/05-concepts/06-database/03-relations/02-one-to-many.md
- docs/05-concepts/06-database/03-relations/03-many-to-many.md
- docs/05-concepts/06-database/08-sort.md
- docs/05-concepts/09-modules.md
- docs/05-concepts/13-scheduling.md
- docs/07-cli.md
- docs/12-upgrading/01-upgrade-to-one-point-two.md
- docs/index.md
All references to `protocol` and `entity` change to `model`. (Except, SerializebleEntity)
> refactor: Rename protocol to model.

- docs/05-concepts/06-database/07-filter.md
The original expression (>= 18 && 65 <=) is confusing for implementation. It should be improved to be clearer, such as  (t.age >= 18) & (t.age <= 65)
> expression improvement to be clear

- docs/05-concepts/06-database/11-migrations.md
Adds a warning that tables not part of the migration system will be removed by a repair migration and need to be managed manually.
> fix: Add warning about repair table removal.

- .github/workflows/test-build.yml
- docs/07-cli.md
Does a simple build of the docs to ensure that it can be published once merged to main.
Also introduces a build on main once it is merged.
Guide followed: https://docusaurus.io/docs/deployment#triggering-deployment-with-github-actions
> ci: Introduce ci build for docs.

- docs/03-tutorials/01-first-app.mdx
- docs/05-concepts/06-database/07-relation-queries.md
- docs/05-concepts/06-database/09-pagination.md
Resolve the last order by syntax issues with the documentation.
> fix: Use new order by syntax for documentation.

- README.md
- versioned_docs/version-1.2.0/05-concepts/06-database/08-sort.md
- versioned_docs/version-1.2.0/05-concepts/06-database/11-migrations.md
- versioned_docs/version-1.2.0/12-upgrading/01-upgrade-to-one-point-two.md
Apply documentation fixes after the release to the 1.2 docs version.
> fix: Apply fixes to 1.2 docs version.

- docs/05-concepts/02-models.md
Add links to the supported datatypes that open the dart API reference.
> fix: Add links to supported datatypes.

- docs/01-get-started.md
- docs/03-tutorials/01-first-app.mdx
A small fix, aim to become clear on contribution requirements before proposing a few more small fix PRs
> fix: model -> models

- docs/12-upgrading/01-upgrade-to-two.md
Add upgrade instructions for unsafeQueryMappedResults that is changes in this PR: https://github.com/serverpod/serverpod/pull/1934.
> fix: add upgrade instructions for unsafeQueryMappedResults

- docs/05-concepts/10-authentication/04-providers/01-email.md
- docs/12-upgrading/01-upgrade-to-two.md
- versioned_docs/version-1.2.0/05-concepts/10-authentication/04-providers/01-email.md
Should not be merged until we release version 1.2.6.
Documents the peppering and secure random configurations.
> Document password hash additions to documentation.

- docs/05-concepts/02-models.md
- versioned_docs/version-1.2.0/05-concepts/02-models.md
Good morning @SandPod , 
As I was already looking into this, I figured I'd try and add it to the documentation :) 
let me know if something needs to be changed 
Ben
Closes: https://github.com/serverpod/serverpod/issues/2055
> add explanation of .spy.yaml to "Working with models"

- docs/05-concepts/10-authentication/04-providers/06-custom-providers.md
- versioned_docs/version-1.2.0/05-concepts/10-authentication/04-providers/06-custom-providers.md
Fixes a small typo (incorrect type assigned to `sessionManager`) in the custom provider guide.
> fix: correct typo in the custom provider guide

- docs/05-concepts/06-database/05-crud.md
- docs/05-concepts/10-authentication/03-working-with-users.md
- versioned_docs/version-1.0.0/04-concepts/07-authentication.md
- versioned_docs/version-1.1.0/04-concepts/09-authentication.md
- versioned_docs/version-1.1.1/05-concepts/09-authentication/03-working-with-users.md
- versioned_docs/version-1.2.0/05-concepts/06-database/05-crud.md
- versioned_docs/version-1.2.0/05-concepts/10-authentication/03-working-with-users.md
Fixes:
- Missing `session` parameter in `updateRow` call
- Unless I'm missing something, the member variable referenced in the docs, `authorizedUserId`, doesn't exist (anymore)?
- I changed it to `authenticatedUserId` which is the existing one
- Is this just a typo and should I change it in all versions of the docs? Or was this a breaking change at some point?
> fix: add missing parameter, change incorrect member variable name

- docs/05-concepts/06-database/05-crud.md
- versioned_docs/version-0.9.10/03-concepts/03-database-communication.md
- versioned_docs/version-0.9.11/03-concepts/03-database-communication.md
- versioned_docs/version-0.9.20/04-concepts/03-database-communication.md
- versioned_docs/version-0.9.21/04-concepts/03-database-communication.md
- versioned_docs/version-0.9.22/04-concepts/03-database-communication.md
- versioned_docs/version-0.9.5/02-concepts/03-database-communication.md
- versioned_docs/version-0.9.6/02-concepts/03-database-communication.md
- versioned_docs/version-0.9.7/03-concepts/03-database-communication.md
- versioned_docs/version-0.9.8/03-concepts/03-database-communication.md
- versioned_docs/version-0.9.9/03-concepts/03-database-communication.md
- versioned_docs/version-1.0.0/04-concepts/03-database-communication.md
- versioned_docs/version-1.1.0/04-concepts/05-database-communication.md
- versioned_docs/version-1.1.1/05-concepts/05-database-communication.md
- versioned_docs/version-1.2.0/05-concepts/06-database/05-crud.md
Added a colon to the limit clause in the db examples to correct the typographical error.
Closes: https://github.com/serverpod/serverpod/issues/2158
> Limit clause update for db examples

- .github/workflows/deploy.yml
When the deploy repo was initialized there probably was a manual step that involved copying over the CNAME file to the docs repo.
Since we now clear out the docs repo between deploys the CNAME file was accidentally removed.
We now always copy over the CNAME file in the deploy pipeline.
> ci: Copy CNAME on docs deploy.

- docs/05-concepts/14-streams.md
- versioned_docs/version-2.0.0/05-concepts/14-streams.md
Closes: https://github.com/serverpod/serverpod_docs/issues/115
> fix: Streams documented with new auth object in session.

- docs/06-concepts/03-serialization.md
- versioned_docs/version-1.2.0/05-concepts/03-serialization.md
- versioned_docs/version-2.0.0/05-concepts/03-serialization.md
- The dependency name of the shared code should be `<projectname>_shared`
> fix: Correct typo in shared dependency

- .github/dependabot.yml
Fixes an issue where docusaurus was not correctly grouped.
> chore: fix grouping for docusaurus dependencies.

- docs/07-deployments/04-deploying-to-aws.md
When running aws deployment guide, I have encountered a few issues. most issues are addressed in https://github.com/serverpod/serverpod/pull/2650/ but for users who has already started with their project, the new cli changes will not be rolled out.
I have also added a few more changes:
1. added documentation for user to change rds url
2. a few line on how to troubleshoot when service doesnt come up
> fix: Add documentation to address AWS deployment issues

- docs/10-contribute.md
- versioned_docs/version-1.0.0/07-contribute.md
- versioned_docs/version-1.1.0/08-contribute.md
- versioned_docs/version-1.1.1/09-contribute.md
- versioned_docs/version-1.2.0/11-contribute.md
- versioned_docs/version-2.0.0/11-contribute.md
- Adds additional aliases that are needed to run integration tests locally
> docs: add all needed host aliases

- docs/01-get-started.md
I wanted to get started with ServerPod but it failed on my chrome browser, since i had ran it before and it worked I was too lazy to debug it so I thought I'll try it out on my iPhone simulator. There it also crashed, then I tried Android emulator, there it worked. Apparently the SocketException on iOS was due to the fact that an iPhone simulator uses localhost for itself. After changing local host to the ip address of my own machine it worked.
> docs: added a new section to getting started for iOS simulator

- docs/06-concepts/06-database/09-pagination.md
cursor description said that the next id was being passed to the client. that is incorrect. it is the id of the last record on the current page
> clarify cursor usage

- docs/06-concepts/06-database/05-crud.md
per discussion [#2814](https://github.com/serverpod/serverpod/discussions/2814#discussioncomment-10864209)
orderBy is exceucted before the list is cut down
> clarify language in info block on findFirstRow

- docs/06-concepts/18-testing/01-get-started.md
- docs/06-concepts/18-testing/02-the-basics.md
- docs/06-concepts/18-testing/03-advanced-examples.md
- docs/06-concepts/18-testing/04-best-practises.md
- docs/06-concepts/18-testing/_category_.json
The idea is to divide into different pages that has different focus areas. Currently I have the following in mind:
- **Get started**: Easily digested get started info, minimum for getting the simplest test to run
- **The basics**: Additional documentation you will absolutely need to know within "the first hour" of writing tests
- **Advanced exmples**: More complex test setup examples. Can still be common cases but not something you necessarily need to write a first test suite.
- **Best practises**: Inspired by Cypress' (e2e web test framework) [best practices page](https://docs.cypress.io/guides/references/best-practices), as inevitably there will always be cases where a user can do a thing in multiple ways. I've found the Cypress page to be tremendously helpful over the years. It also …
> feat: Add test tools docs

- docs/06-concepts/06-database/06-filter.md
- docs/06-concepts/06-database/07-relation-queries.md
- versioned_docs/version-1.2.0/05-concepts/06-database/06-filter.md
- versioned_docs/version-1.2.0/05-concepts/06-database/07-relation-queries.md
- versioned_docs/version-2.0.0/05-concepts/06-database/06-filter.md
- versioned_docs/version-2.0.0/05-concepts/06-database/07-relation-queries.md
- versioned_docs/version-2.1.0/06-concepts/06-database/06-filter.md
- versioned_docs/version-2.1.0/06-concepts/06-database/07-relation-queries.md
- [This PR aligned](https://github.com/serverpod/serverpod_docs/commit/ea118fbc641e2fc9c25e1c98ec169cb63d6ee0b7) the docs so that `iLike` was used everywhere (it was mixed in the docs before this PR).
- However, the correct casing is actually `ilike`, which this PR addresses.
- Changes `iLike` to `ilike` 
- Adds code highlighting to `ilike`
> fix: Change incorrect casing `iLike` to `ilike`.

- docs/06-concepts/18-testing/01-get-started.md
- docs/06-concepts/19-experimental.md
- The test tools experimental flag was missing from the experimental flags page.
> fix: add test tools experimental flag to the experimental page

- docs/06-concepts/18-testing/01-get-started.md
- Main change is to add the missing step to add `serverpod_test` package
- Changes the example test to actually pass for the default example endpoint
- Small reformats to make it more user friendly
> fix: Add missing step for existing project

- docs/06-concepts/18-testing/01-get-started.md
I'm pretty sure this should be 'is', as 'test tools' is singular (it's just one feature).
> fix: Grammar on get started with tests page.

- docs/06-concepts/15-streams.md
- versioned_docs/version-2.0.0/05-concepts/14-streams.md
- versioned_docs/version-2.1.0/06-concepts/15-streams.md
> fix: Correct wrong name of authenticationInfo variable.

- docs/06-concepts/18-testing/01-get-started.md
- Fixes an error where the db user name was wrong in the docker compose
> fix: Incorrect db user name in docker compose.

- docs/01-get-started.md
- versioned_docs/version-1.1.1/01-get-started.md
- versioned_docs/version-1.2.0/01-get-started.md
- versioned_docs/version-2.0.0/01-get-started.md
- versioned_docs/version-2.1.0/01-get-started.md
Because there is an `employees` field with type `List<Employee>` in the company definition, running `serverpod generate`serverpod generate fails with `The field has an invalid datatype "Employee".` error. 
Later in the docs in the [Object database mapping](https://docs.serverpod.dev/get-started#object-database-mapping) section, there is no employees field, so I'm guessing it's okay to remove it.
> fix: Remove the unreferenced List of Employee from the get-started doc

- docs/06-concepts/19-experimental.md
This is the documentation part of https://github.com/serverpod/serverpod/pull/2888
To the existing example a h3 and a short intro is added for "Extending a Class", and a h3, intro and example was added explaining the sealed classes. 
Please let me know where there is room for improvement :rocket:
> document the sealed feature

- docs/06-concepts/18-testing/02-the-basics.md
- docs/06-concepts/18-testing/03-advanced-examples.md
- Adds docs for new config options
- Adds an example for when max connections limit is hit
> fix: Add new configuration options, add example.

- docs/06-concepts/18-testing/01-get-started.md
Found a missing `=` in the bash command
> add missing equals sign to bash command

- .markdownlint.yaml
- docs/08-upgrading/04-upgrade-to-two-point-two.md
- Adds an upgrade page for Serverpod version 2.2
> docs: add upgrade to 2.2 page

- docs/06-concepts/06-database/03-relations/05-referential-actions.md
- versioned_docs/version-1.2.0/05-concepts/06-database/03-relations/05-referential-actions.md
- versioned_docs/version-2.0.0/05-concepts/06-database/03-relations/05-referential-actions.md
- versioned_docs/version-2.1.0/06-concepts/06-database/03-relations/05-referential-actions.md
Our current documentation didn't reflect the real default refential action values.
This was brought up in a discussion thread around how referential actions work: https://github.com/serverpod/serverpod/discussions/3008
This PR documents the correct behavior for object and id relations.
> fix: Update default refential action values.

- docs/06-concepts/06-database/08-transactions.md
Closes: https://github.com/serverpod/serverpod/issues/3050
Adds documentation for transaction isolation level.
Also updates the description for transactions a bit to better reflect the current state of the code.
Image of the documentation:
After review:
> fix: Add documentation for transaction isolation level.

- docs/01-get-started.md
- docs/06-concepts/01-working-with-endpoints.md
Closes: [#3052](https://github.com/serverpod/serverpod/issues/3052)
Updates the documentation to reflect that endpoints can now be placed anywhere in the **lib** directory.
I didn't add any information for the tutorials since these are case examples.
Do we think this is enough, or does it need to be clarified more?
**Changes in get started**
**Changes in working with endpoints**
--------------------------------------
> fix: Document free endpoint defintion placement.

- docs/07-deployments/04-deploying-to-aws.md
- versioned_docs/version-0.9.10/04-deployments/01-deploying-to-aws.md
- versioned_docs/version-0.9.11/04-deployments/01-deploying-to-aws.md
- versioned_docs/version-0.9.20/05-deployments/01-deploying-to-aws.md
- versioned_docs/version-0.9.21/05-deployments/01-deploying-to-aws.md
- versioned_docs/version-0.9.22/05-deployments/01-deploying-to-aws.md
- versioned_docs/version-0.9.8/04-deployments/01-deploying-to-aws.md
- versioned_docs/version-0.9.9/04-deployments/01-deploying-to-aws.md
- versioned_docs/version-1.0.0/05-deployments/01-deploying-to-aws.md
- versioned_docs/version-1.1.0/05-deployments/04-deploying-to-aws.md
- versioned_docs/version-1.1.1/06-deployments/04-deploying-to-aws.md
- versioned_docs/version-1.2.0/06-deployments/04-deploying-to-aws.md
- versioned_docs/version-2.0.0/06-deployments/04-deploying-to-aws.md
- versioned_docs/version-2.1.0/07-deployments/04-deploying-to-aws.md
- versioned_docs/version-2.2.0/07-deployments/04-deploying-to-aws.md
- versioned_docs/version-2.3.0/07-deployments/04-deploying-to-aws.md
Wasted an hour because I didn't see that there is `aws_region` field. 
It might take sense to you, but to a newcomer, I think it's weird that docs are talking about changing `ami_instance` and never mention the `aws_region` field.
> Add more info when changing aws region

- .github/ISSUE_TEMPLATE/config.yml
Prevents issues from being created in the docs repository and refer them to the Serverpod repo.
Creating a new issue in this repository will now display this prompt
Directing you to this page:
> chore: Add issue template pointing towards serverpod.

- .github/workflows/title-validation.yml
Adds a PR title validator inspired by the configuration for the flame open source repository: https://github.com/flame-engine/flame/blob/main/.github/ISSUE_TEMPLATE/feature_request.yml?plain=1
Since PR titles are by default used as the commit message to main, this linter will help us ensure we follow conventional commits for the squashes in main.
> chore: Add PR title validator

- docs/06-concepts/19-testing/01-get-started.md
Updates the documentation to match the changes introduced in this PR: https://github.com/serverpod/serverpod/pull/3192
The PR removed the profiles from the Docker Compose to simplify the setup and make it windows compatible.
Only adding this to the "next" documentation since the change will be part of the next Serverpod release (2.4.0)
Closes: https://github.com/serverpod/serverpod/issues/3143
> fix: Remove mention of profiles in documentation.

- docs/06-concepts/07-configuration.md
Adds documentation for the new SERVERPOD_SERVER_ID environment variable introduced in this PR: https://github.com/serverpod/serverpod/pull/3238
We should make the other command line options equally configurable through environment variables.
> fix: Add documentation for SERVERPOD_SERVER_ID

- docs/07-deployments/04-deploying-to-aws.md
- versioned_docs/version-2.3.0/07-deployments/04-deploying-to-aws.md
- versioned_docs/version-2.4.0/07-deployments/04-deploying-to-aws.md
This typo was fixed in this PR https://github.com/serverpod/serverpod/pull/2976 and shipped with 2.3.0.
This fixes the typo for the newer versions.
Noticed and originally fixed by @damolator in https://github.com/serverpod/serverpod_docs/pull/250
> fix: Fixes a typo that was fixed in the repo in 2.3.0

- docs/06-concepts/01-working-with-endpoints.md
- docs/06-concepts/17-backward-compatibility.md
* `@ignoreEndpoint` annotation on classes and methods.
* Endpoint inheritance.
* Endpoint inheritance from abstract classes.
* Versioning your API (Inheritance + deprecated annotation + changes in new API).
> docs: Add documentation for `Endpoint` inheritance

- docs/06-concepts/01-working-with-endpoints.md
- docs/06-concepts/17-backward-compatibility.md
instead of deprecated `@ignoreEndpoint`
Based upon https://github.com/serverpod/serverpod/pull/3484
Closes https://github.com/serverpod/serverpod/issues/3478
> docs: Update documentation to refer to new `@doNotGenerate` annotation

- docs/06-concepts/07-configuration.md
- docs/06-concepts/14-scheduling.md
Adds documentation for the new configuration option on future calls.
---- 
----
----
> fix: Add documentation for concurrent future calls

- docs/06-concepts/02-models.md
Adds documentation for the new UUIDv7 default option.
> fix: Add documentation for uuidv7 default option.

- docs/06-concepts/06-database/11-migrations.md
- versioned_docs/version-1.2.0/05-concepts/06-database/11-migrations.md
- versioned_docs/version-2.0.0/05-concepts/06-database/11-migrations.md
- versioned_docs/version-2.1.0/06-concepts/06-database/11-migrations.md
- versioned_docs/version-2.2.0/06-concepts/06-database/11-migrations.md
- versioned_docs/version-2.3.0/06-concepts/06-database/11-migrations.md
- versioned_docs/version-2.4.0/06-concepts/06-database/11-migrations.md
- versioned_docs/version-2.5.0/06-concepts/06-database/11-migrations.md
- versioned_docs/version-2.6.0/06-concepts/06-database/11-migrations.md
- versioned_docs/version-2.7.0/06-concepts/06-database/11-migrations.md
- versioned_docs/version-2.8.0/06-concepts/06-database/11-migrations.md
Adds the full instructions on how to do the rollback - if someone does not read the whole page but jumps to the section in the navigation they will not necessarily know where to look
> docs: Add full rollback example

- docs/09-tools/01-insights.md
- versioned_docs/version-1.2.0/08-insights.md
- versioned_docs/version-2.0.0/07-tools/02-insights.md
- versioned_docs/version-2.1.0/09-tools/01-insights.md
- versioned_docs/version-2.2.0/09-tools/01-insights.md
- versioned_docs/version-2.3.0/09-tools/01-insights.md
- versioned_docs/version-2.4.0/09-tools/01-insights.md
- versioned_docs/version-2.5.0/09-tools/01-insights.md
- versioned_docs/version-2.6.0/09-tools/01-insights.md
- versioned_docs/version-2.7.0/09-tools/01-insights.md
- versioned_docs/version-2.8.0/09-tools/01-insights.md
- versioned_docs/version-2.9.0/09-tools/01-insights.md
Bumps the link to the newest version.
Here are the links to test:
https://downloads.serverpod.dev/macos/Serverpod-2.9.1.zip
https://downloads.serverpod.dev/windows/serverpod-2.9.1.zip
> chore: Update link to use 2.9.1 insights version.

- docs/01-get-started/01-creating-endpoints.md
- docs/01-get-started/02-models-and-data.md
- docs/01-get-started/03-working-with-the-database.md
- versioned_docs/version-2.7.0/01-get-started/01-creating-endpoints.md
- versioned_docs/version-2.7.0/01-get-started/02-models-and-data.md
- versioned_docs/version-2.7.0/01-get-started/03-working-with-the-database.md
- versioned_docs/version-2.8.0/01-get-started/01-creating-endpoints.md
- versioned_docs/version-2.8.0/01-get-started/02-models-and-data.md
- versioned_docs/version-2.8.0/01-get-started/03-working-with-the-database.md
- versioned_docs/version-2.9.0/01-get-started/01-creating-endpoints.md
- versioned_docs/version-2.9.0/01-get-started/02-models-and-data.md
- versioned_docs/version-2.9.0/01-get-started/03-working-with-the-database.md
Heya, found a small bug in the getting started guide and wanted to fix it up!
1. Follow the gettin started guide
2. Blindly copy-paste the server endpoint code into my project
3. Update the Flutter app as well
4. Run the app
5. Try to get a recipe -- Oh no! Internal server error
```
2025-09-26 13:35:07.499922Z  558569213 ERROR          n/a                      Publisher Model `projects/generativelanguage-ga/locations/us-central1/publishers/google/models/gemini-1.5-flash-002` was not found or your project does not have access to it. Please ensure you are using a valid model version. For more information, see: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions
```
By following the link in the error message above, it looks like the name of the [auto-updated …
> fix: Gemini model in getting started guide

- docs/06-concepts/01-working-with-endpoints.md
Documentation for the feature introduced at https://github.com/serverpod/serverpod/pull/4023.
> docs: Add documentation for client-side endpoint inheritance
